### ISSUE TITLE
STT0063: STT wav2vec2 model training with latest data plus addition of noise in training data.

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/stt-wav2vec2#8]
### Description 
We have to train our wav2vec2 model on the latest dataset we have and also include noise in training data so that our model become more robust in performance under noisy conditions.
### Completion Criteria 
A more robust and accurate model than our previous wav2vec2 model.
### Implementation 
1. Run combine all to get our latest data.
2. add noise to the training data. (5% of each department training data)
3. train the model .
4. evaluate the model
### Subtask
- [x] run combine all to all get all latest datasets
- [x] download all the audios from url in gcp instance 
- [x] add noise to 5 percent portion of training data of each department
- [x] run prepare dataset to convert training data to model expected input format
- [x] train the model
- [x] evaluate the model on benchmark dataset
